-- script drop procedures
DROP TRIGGER IF EXISTS addPersonneCours;
DROP TRIGGER IF EXISTS poids_max_poneys;
DROP TRIGGER IF EXISTS paye;
DROP TRIGGER IF EXISTS repos;
DROP TRIGGER IF EXISTS poney_participant;

-- script de suppression des tables
DROP TABLE IF EXISTS ENCADRER;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ETRE_PRESENT;
DROP TABLE IF EXISTS TARIFS;
DROP TABLE IF EXISTS FACTURE;
DROP TABLE IF EXISTS SOLLICITER;
DROP TABLE IF EXISTS PARTICIPER;
DROP TABLE IF EXISTS PONEY;
DROP TABLE IF EXISTS SEANCE;
DROP TABLE IF EXISTS COURS;
DROP TABLE IF EXISTS ADHERENT;
DROP TABLE IF EXISTS MONITEUR;
DROP TABLE IF EXISTS PERSONNE;
DROP TABLE IF EXISTS SEANCE;
